-- MySQL Script generated by MySQL Workbench
-- Mon Oct  8 12:32:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bancotcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bancotcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancotcc` DEFAULT CHARACTER SET utf8 ;
USE `bancotcc` ;

-- -----------------------------------------------------
-- Table `bancotcc`.`TbEspecie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`TbEspecie` (
  `especieId` INT NOT NULL AUTO_INCREMENT,
  `especieNome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`especieId`),
  UNIQUE INDEX `tipousuarioId_UNIQUE` (`especieId` ASC) ,
  UNIQUE INDEX `tipousuarioNome_UNIQUE` (`especieNome` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`TbUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`TbUsuario` (
  `usuarioId` INT NOT NULL AUTO_INCREMENT,
  `usuarioNomeCompleto` VARCHAR(255) NOT NULL,
  `usuarioEmail` VARCHAR(150) NOT NULL,
  `usuarioSenha` VARCHAR(50) NOT NULL,
  `usuarioDataCadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuarioSexo` CHAR NOT NULL,
  `TbEspecie_especieId` INT NOT NULL,
  PRIMARY KEY (`usuarioId`, `TbEspecie_especieId`),
  UNIQUE INDEX `usuario_id_UNIQUE` (`usuarioId` ASC) ,
  UNIQUE INDEX `usuario_email_UNIQUE` (`usuarioEmail` ASC) ,
  INDEX `fk_TbUsuario_TbEspecie1_idx` (`TbEspecie_especieId` ASC) ,
  CONSTRAINT `fk_TbUsuario_TbEspecie`
    FOREIGN KEY (`TbEspecie_especieId`)
    REFERENCES `bancotcc`.`TbEspecie` (`especieId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`TbQuestao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`TbQuestao` (
  `questaoId` INT NOT NULL AUTO_INCREMENT,
  `questaoNome` VARCHAR(100) NOT NULL,
  `questaoDescricao` TEXT NOT NULL,
  `questaoDataCriacao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `questaoAssunto` TEXT NOT NULL,
  `questaoDificuldade` INT NOT NULL,
  `questaoDados` TEXT NOT NULL,
  PRIMARY KEY (`questaoId`),
  UNIQUE INDEX `questaoId_UNIQUE` (`questaoId` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`TbAlternativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`TbAlternativa` (
  `alternativaId` INT NOT NULL AUTO_INCREMENT,
  `alternativaTexto` TEXT NOT NULL,
  `alternativacorreta` TINYINT NOT NULL DEFAULT 0,
  `TbQuestao_questaoId` INT NOT NULL,
  PRIMARY KEY (`alternativaId`, `TbQuestao_questaoId`),
  UNIQUE INDEX `alternativaId_UNIQUE` (`alternativaId` ASC) ,
  INDEX `fk_TbAlternativa_TbQuestao1_idx` (`TbQuestao_questaoId` ASC) ,
  CONSTRAINT `fk_TbAlternativa_TbQuestao1`
    FOREIGN KEY (`TbQuestao_questaoId`)
    REFERENCES `bancotcc`.`TbQuestao` (`questaoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`TbSubmissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`TbSubmissao` (
  `submissaoId` INT NOT NULL AUTO_INCREMENT,
  `submissaoData` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `submissaoDados` TEXT NOT NULL,
  `TbVeredito_vereditoId` INT NOT NULL,
  `TbAlternativa_alternativaId` INT NOT NULL,
  `TbUsuario_usuarioId` INT NOT NULL,
  `TbQuestao_questaoId` INT NOT NULL,
  PRIMARY KEY (`submissaoId`, `TbVeredito_vereditoId`, `TbAlternativa_alternativaId`, `TbUsuario_usuarioId`, `TbQuestao_questaoId`),
  UNIQUE INDEX `submissaoId_UNIQUE` (`submissaoId` ASC) ,
  INDEX `fk_TbSubmissao_TbAlternativa1_idx` (`TbAlternativa_alternativaId` ASC) ,
  INDEX `fk_TbSubmissao_TbUsuario1_idx` (`TbUsuario_usuarioId` ASC) ,
  INDEX `fk_TbSubmissao_TbQuestao1_idx` (`TbQuestao_questaoId` ASC) ,
  CONSTRAINT `fk_TbSubmissao_TbAlternativa1`
    FOREIGN KEY (`TbAlternativa_alternativaId`)
    REFERENCES `bancotcc`.`TbAlternativa` (`alternativaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TbSubmissao_TbUsuario1`
    FOREIGN KEY (`TbUsuario_usuarioId`)
    REFERENCES `bancotcc`.`TbUsuario` (`usuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TbSubmissao_TbQuestao1`
    FOREIGN KEY (`TbQuestao_questaoId`)
    REFERENCES `bancotcc`.`TbQuestao` (`questaoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`TbModulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`TbModulo` (
  `moduloId` INT NOT NULL AUTO_INCREMENT,
  `moduloNome` VARCHAR(100) NOT NULL,
  `moduloDescricao` TEXT NOT NULL,
  PRIMARY KEY (`moduloId`),
  UNIQUE INDEX `moduloId_UNIQUE` (`moduloId` ASC) ,
  UNIQUE INDEX `moduloNome_UNIQUE` (`moduloNome` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`TbQuestaoModulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`TbQuestaoModulo` (
  `TbQuestao_questaoId` INT NOT NULL,
  `TbModulo_moduloId` INT NOT NULL,
  PRIMARY KEY (`TbQuestao_questaoId`, `TbModulo_moduloId`),
  INDEX `fk_TbQuestaoModulo_TbModulo1_idx` (`TbModulo_moduloId` ASC) ,
  CONSTRAINT `fk_TbQuestaoModulo_TbQuestao1`
    FOREIGN KEY (`TbQuestao_questaoId`)
    REFERENCES `bancotcc`.`TbQuestao` (`questaoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TbQuestaoModulo_TbModulo1`
    FOREIGN KEY (`TbModulo_moduloId`)
    REFERENCES `bancotcc`.`TbModulo` (`moduloId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
